/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 donut.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/donut.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Donut.geometry} material={materials['Material.001']} position={[-0.087, -0.543, -0.115]} scale={8.15} />
      <mesh geometry={nodes.Icing.geometry} material={materials['Material.002']} position={[0.036, -0.018, -0.012]} scale={8.15} />
    </group>
  )
}

useGLTF.preload('/donut.gltf')
